name: my first wf
on:
    workflow_dispatch:
jobs:
     ali:
      runs-on: ubuntu-latest
      steps:
          - name: welcome msg
<<<<<<< HEAD
            run: echo "hello msg"
=======
            run: echo "hello msg"

>>>>>>> 27783d53864527a821ca60db90808c6d9277c099