name: my third wf
on:
    workflow_dispatch:
jobs:
    first-job:
      runs-on: ubuntu-latest
      steps:
          - name: install cowsay program
            run: sudo apt-get install cowsay -y

          - name: execute cowsay program
            run: cowsay -f dragon "Run for cover" >> dragon.txt

          - name: test file exists
            run: grep -i "cover" dragon.txt

          - name: read file
            run: cat dragon.txt

          - name: check repo fils
            run: ls
        
          - uses: actions/upload-artifact@v4
            with:
                path: dragon

    test-job:
      needs: first-job
      runs-on: ubuntu-latest
      steps:
         
          
          - uses: actions/download-artifact@v4
            with:
                path: dragon

          - name: verify list
            run: ls -l 

    deploy-job:
      needs: test-job
      runs-on: ubuntu-latest
      steps:
         
          
          - uses: actions/download-artifact@v4
            with:
                path: dragon

          - name: unzip
            run: unzip dragon.zip

          - name: read file
            run: cat dragon.txt