name: my third wf
on:
    workflow_dispatch:
jobs:
    first-job:
      runs-on: ubuntu-latest
      steps:
          - name: install cowsay program
            run: sudo apt-get install cowsay -y

          - name: execute cowsay program
            run: cowsay -f dragon "Run for cover" >> dragon.txt
        
          - uses: actions/upload-artifact@v4
            with:
                name: dragon-file
                path: dragon.txt

    test-job:
      needs: first-job
      runs-on: ubuntu-latest
      steps:
           
          - uses: actions/download-artifact@v4
            with:
                name: dragon-file

          - name: verify list
            run: ls -l 

    deploy-job:
      needs: test-job
      runs-on: ubuntu-latest
      steps:
         
          - uses: actions/download-artifact@v4
            with:
                name: dragon-file
                path: dragon

          - name: unzip the dragon-file
            run: unzip dragon-file.zip

          - name: read file
            run: cat dragon.txt